Orena/250319_문자열을_정수로_바꾸기.java
Orena/250319_약수의_합.java
Orena/250319_자릿수_더하기.java
Orena/250320_x만큼_간격이_있는_n개의_숫자.java
Orena/250320_나머지가_1이_되는_수_찾기.java
Orena/250320_자연수_뒤집어_배열로_만들기.java
Orena/250320_짝수와_홀수.java
Orena/250320_평균_구하기.java
Orena/250321_두_정수_사이의_합.java
Orena/250321_문자열_내_p와_y의_개수.java
Orena/250321_정수_내림차순으로_배치하기.java
Orena/250322_정수_제곱근_판별.java
Orena/250322_하샤드_수.java
Orena/250324_없는_숫자_더하기.java
Orena/250324_음양_더하기.java
Orena/250325_나누어_떨어지는_숫자_배열.java
Orena/250325_서울에서_김서방_찾기.java

19일부터 24일까지 총 15문제입니다.
확인 부탁드립니다.

feat: 250324 15문제

---

99MotiveU/250325_나누어_떨어지는_숫자_배열.java
99MotiveU/250325_서울에서_김서방_찾기.java

feat: 99MotiveU 250325 2문제

---

HbinAhn/250324_나누어_떨어지는_숫자배열.java
HbinAhn/250324_음양_더하기.java
HbinAhn/250325_서울에서_김서방_찾기.java
HbinAhn/250325_없는_숫자_더하기.java

feat: HbinAhn 250325 4문제

---

minho00123/250319_문자열을_정수로_바꾸기.java
minho00123/250319_약수의_합.java
minho00123/250319_자릿수_더하기.java
minho00123/250320_x만큼_간격이_있는_n개의_숫자.java
minho00123/250320_나머지가_1이_되는_수_찾기.java
minho00123/250320_자연수_뒤집어_배열로_만들기.java
minho00123/250320_짝수와_홀수.java
minho00123/250320_평균_구하기.java
minho00123/250321_두_정수_사이의_합.java
minho00123/250321_문자열_내_p와_y의_개수.java
minho00123/250321_정수_내림차순으로_배치하기.java
minho00123/250322_정수_제곱근_판별.java
minho00123/250322_하샤드_수.java
minho00123/250324_나누어_떨어지는_숫자_배열.java
minho00123/250324_음양_더하기.java
minho00123/250325_서울에서_김서방_찾기.java
minho00123/250325_없는_숫자_더하기.java

이전에 3월 19일부터 풀었던 문제를 포함한 내용입니다.

feat: minho00123 250325 17문제

---

nojong99/250325_나누어_떨어지는_숫자_배열.java
nojong99/250325_서울에서_김서방_찾기.java

ArrayList를 다루었고, String.format에 대해 배우게 되었습니다.

feat: nojong99 250325 2문제

---

Orena/250326_가운데_글자_가져오기.java
Orena/250326_콜라츠_추측.java

콜라츠 추측은 조건문, 반복문 사용했고,
가운데 글자 가져오기는 substring 사용해봤습니다.

feat: Orena 250326 2문제

---

99MotiveU/250326_가운데_글자_가져오기.java
99MotiveU/250326_콜라츠_추측.java

feat: 99MotiveU 250326 2문제

---

nojong99/250326_가운데_글자_가져오기.java
nojong99/250326_콜라츠_추측.java

문제의 조건에 맞춰 변수의 타입을 유동적으로 바꿔야 한다는 것을 배웠습니다.

feat: nojong99 250326 2문제

---

minho00123/250327_수박수박수박수박수박수.java
minho00123/250327_약수의_개수와_덧셈.java

약수의 개수와 덧셈 문제는 규칙을 찾아 적용해보았습니다.
만약 주어진 수가 제곱근을 진행하였을 때 정수가 나오면 약수의 개수가 홀수가 된다는 점을 이용하였습니다.

feat: minho00123 250327 2문제

---

nojong99/250327_수박수박수박수박수박수.java
nojong99/250327_약수의_개수와_덧셈.java

feat: nojong99 250327 2문제

---

HbinAhn/250327_수박수박수박수박수박수.java
HbinAhn/250327_약수의_개수와_덧셈.java

반복문을 만들때 특정 수를 초기화시켜줘야 한다는 걸 유의해야 한다는 점을 배웠습니다.

feat: HbinAhn 250327 2문제

---

99MotiveU/250327_수박수박수박수박수박수.java
99MotiveU/250327_약수의_개수와_덧셈.java

수박수박수박수박수박수는 Java는 문자열 덧셈이 가능하다는 점을 이용해 쉽게 접근했고, 약수의 개수와 덧셈 문제는 주어진 수가 제곱수일 경우에 약수의 개수가 홀수인 점을 이용해 해결했습니다.

feat: 99MotiveU 250327 2문제

---

minho00123/250328_같은_숫자는_싫어.java
minho00123/250328_최대공약수와_최소공배수.java

feat: minho00123 250328 2문제

---

nojong99/250328_같은_숫자는_싫어.java
nojong99/250328_최대공약수와_최소공배수.java

feat: nojong99 250328 2문제

---

HbinAhn/250328_같은_숫자는_싫어.java
HbinAhn/250328_최대공약수와_최소공배수.java

덕분에 for문을 반복해서 쓸 때 중복되지 않게 주의해야 하는 점과 오류가 날 경우 출력문을 통해 과정을 확인하는 방법을 배울 수 있었습니다. 감사합니다!

feat: HbinAhn 250328 2문제

---

Orena/250328_같은_숫자는_싫어.java
Orena/250328_최대공약수와_최소공배수.java

같은 숫자는 싫어는 ArrayList를 활용했고 최대공약수는 코드를 좀 더 줄이고 싶었는데 어려웠네요. 오늘도 수고하셨습니다.

feat: Orena 250328 2문제

---

Orena/250329_3진법_뒤집기.java
Orena/250329_예산.java
Orena/250331_삼총사.java
Orena/250331_크기가_작은_부분문자열.java

3월 29일, 3월 31일 총 4문제입니다.
3진법은 int배열을 사용해 풀었고 
삼총사는 재귀 함수를 공부하여 풀었습니다.

feat: Orena 250331 4문제

---

HbinAhn/250329_3진법_뒤집기.java
HbinAhn/250329_예산.java
HbinAhn/250331_삼총사.java
HbinAhn/250331_크기가_작은_부분문자열.java

3진법 뒤집기에서 처음 Stack을 활용해 풀어봤습니다. 삼총사 문제의 삼중 for문은 더 노력해보겠습니다!

feat: HbinAhn 250331 4문제

---

minho00123/250329_3진법_뒤집기.java
minho00123/250329_예산.java
minho00123/250331_삼총사.java
minho00123/250331_크기가_작은_부분_문자열.java

토요일날 2문제 커밋하고, 오늘 2문제 커밋하였습니다.

feat: minho00123 250331 4문제

---

99MotiveU/250329_3진법_뒤집기.java
99MotiveU/250329_예산.java
99MotiveU/250331_삼총사.java
99MotiveU/250331_크기가_작은_부분_문자열.java

feat: 99MotiveU 250331 4문제

---

nojong99/250329_3진법_뒤집기.java
nojong99/250329_예산.java
nojong99/250331_삼총사.java
nojong99/250331_크기가_작은_부분문자열.java

3진법 뒤집기 문제는 처음  실행 했을 때 시간 초과 오류가 났었습니다. string 은 불변 객체라 값을 바꿀 때 마다 새로운 객체를 생성해야 하기 때문입니다.  또, Integer.parseInt를 통해 뒤의 숫자로 진법을 바꿀 수 있다는 것을 배웠습니다. 
삼총사 문제는  스택을 사용하였지만  스택의 연산을 수행해야 하는 복잡성 때문에 3중 for문 보다 효율이 좋지 않다고 합니다.

feat: nojong99 250331 4문제

---

99MotiveU/250401_이상한_문자_만들기.java
99MotiveU/250401_최소직사각형.java

feat: 99MotiveU 250401 2문제

---

HbinAhn/250401_이상한_문자_만들기.java
HbinAhn/250401_최소직사각형.java

이중 배열을 다루는데 좀 더 익숙해질 수 있는 경험이었습니다. split에 대한 공부도 추가로 할 수 있어 좋은 문제였습니다!

feat: HbinAhn 250401 2문제

---

Orena/250401_이상한_문자_만들기.java
Orena/250401_최소직사각형.java

이상한 문자 만들기는 split으로 string 배열 만들어서 풀었고 
최소직사각형은 Math의 max와 min을 활용해 풀었습니다.

feat: Orena 250401 2문제

---

minho00123/250402_가장_가까운_같은_글자.java
minho00123/250402_시저_암호.java

시저 암호는 ASCII 코드를 이용하여 풀이를 진행하였습니다.
가장 가까운 같은 글자는 Map을 이용하여 풀이해보았습니다.

feat: minho00123 250402 2문제

---

nojong99/250402_가장_가까운_같은_글자.java
nojong99/250402_시저_암호.java

char 자료형의 값을 다루는 문제들이라 어려웠지만, (char) 강제 타입 변환으로 해결을 해주었습니다. ^^

feat: nojong99 250402 2문제

---

HbinAhn/250402_가장_가까운_같은_글자.java
HbinAhn/250402_시저_암호.java

가장 가까운 같은 글자는 알고리즘을 찾는 과정 자체가, 시저 암호는 char-> int-> char로 전환시키는 과정을 고민해볼 수 있어 좋은 문제였습니다.

feat: HbinAhn 250402 2문제

---

99MotiveU/250402_가장_가까운_같은_글자.java
99MotiveU/250402_시저_암호.java

4/2 "시저 암호"와 가장 "가까운 같은 글자" 문제 입니다

feat: 99MotiveU 250402 2문제

---

shong69/250402_가장_가까운_같은_글자.java
shong69/250402_시저_암호.java
shong69/250403_K번째수.java
shong69/250403_두_개_뽑아서_더하기.java

'가장 가까운 글자'에서 lastIndexOf()를 사용해봤습니다.
+) 250403
stream을 사용하여 풀어보았습니다.

feat : shong69 250402 2문제

---

minho00123/250403_K번째수.java
minho00123/250403_두_개_뽑아서_더하기.java

Arrays 메서드와 Set을 이용하여 문제를 풀이하였습니다.

feat: minho00123 250403 2문제

---

nojong99/250403_K번째수.java
nojong99/250403_두_개_뽑아서_구하기.java

K번째수는 ArrayList를 사용했습니다.
두 개 뽑아서 구하기는 Treeset을 사용했습니다.  ^^

feat: nojong99 250403 2문제

---

HbinAhn/250403_k번째수.java
HbinAhn/250403_두_개_뽑아서_더하기.java

arraylist를 배열로 만들때 iterator 쓰는 방법을 활용해볼 수 있어 좋았습니다.

feat: HbinAhn 250403 2문제

---

Orena/250403_K번째수.java
Orena/250403_두_개_뽑아서_더하기.java
Orena/250404_숫자_문자열과_영단어.java
Orena/250404_푸드_파이트_대회.java

K번째수는 이중배열을 이용해서 풀었고 
두 개 뽑아서 더하기는 set을 이용하여 풀었습니다.

feat: Orena 250403 2문제

---

minho00123/250404_숫자_문자열과_영단어.java
minho00123/250404_푸드_파이트_대회.java

숫자 문자열과 영단어는 배열을 이용하여 String 메서드를 사용하였습니다.
푸드 파이트 대회는 가운데 0을 기준으로 앞부분은 앞에서부터, 뒷부분은 뒤에서부터 for문을 돌려 값을 도출하였습니다.

feat: minho00123 250404 2문제

---

99MotiveU/250403_K번째수.java
99MotiveU/250403_두_개_뽑아서_더하기.java
99MotiveU/250404_숫자_문자열과_영단어.java
99MotiveU/250404_푸드_파이트_대회.java

늦어서 죄송합니다. 익숙하지 않은 방식으로 해보다 보니 좀 더 걸렸습니다.

feat: 99MotiveU 250403 2문제

---

nojong99/250404_숫자_문자열과_영단어.java
nojong99/250404_푸드_파이트_대회.java

숫자 문자열과 영단어 문제는 String 배열과 replace함수를 사용하여 해결하였고,
푸드 파이트 대회는 String.valueOf로 해결하였습니다.

feat: nojong99 250404 2문제

---

HbinAhn/250414_문자열_내_마음대로_정렬하기.java
HbinAhn/250414_콜라_문제.java

문자열 내 마음대로 정렬하기 문제의 경우, Comparator를 활용해 compare 메서드 오버라이드하는 방법을 찾아 풀게 되었습니다. 이 문제를 통해 Comparator를 사용한 정렬 방법, Charactor.compare, String.compareTo를 활용하는 방법을 배웠습니다.

feat: HbinAhn 250414 2문제

---

shong69/250414_문자열_내_마음대로_정렬하기.java
shong69/250414_콜라_문제.java
shong69/250415_[1차]비밀지도.java

[콜라문제]는 규칙을 찾아 while문으로 문제를 해결하였습니다.
[문자열 내 마음대로 정렬하기]에서는 Arrays.sort를 사용해 복합 정렬을 구현하였습니다.

feat: shong69 250414 2문제

---

99MotiveU/250414_문자열_내_마음대로_정렬하기.java
99MotiveU/250414_콜라_문제.java

콜라문제는 문제 그대로 코드로 쓰면서 쉽게 풀었고 문자열 내 마음대로 정렬하기는 compareTo를 활용해 풀었습니다.

feat: 99MotiveU 250414 2문제

---

Orena/250415_[1차]_비밀지도.java

2진수로 계산하여 OR 연산자로 1이 있는 배열의 위치에 "#"을 넣는 방식으로 풀었습니다.

feat: Orena 250415 1문제

---

minho00123/250415_1차_비밀지도.java

이진수를 자릿수에 맞춰 변환한 후에 벽인지, 공백인지를 구분하여 풀이하였습니다.

feat: minho00123 250415 1문제

---

nojong99/250415_[1차]_비밀지도.java

비밀지도 문제는 이중 for문을 통해 문제를 해결하였습니다.

feat: nojong99 250415 1문제

---

HbinAhn/250415_1차_비밀지도.java

array 접근 방식이 정말 고민되었던 것같습니다. 도움 주신 덕분에 풀 수 있었습니다.
method로 arr1, 2를 2진법 숫자로 하나씩 전환-> 전환한 String 타입 숫자를 equals로 하나씩 비교하는 방법을 사용하였습니다.

feat: HbinAhn 250415 1문제

---

99MotiveU/250415_[1차]_비밀지도.java

feat: 99MotiveU 250415 1문제

---

minho00123/250416_추억_점수.java
minho00123/250416_카드_뭉치.java

카드 뭉치는 각각의 인덱스를 활용하여 문제를 풀었습니다.
추억 점수는 각각의 배열을 for문으로 돌면서 풀이를 진행하였습니다.

feat: minho00123 250416 2문제

---

Orena/250416_추억_점수.java
Orena/250416_카드_뭉치.java

카드 뭉치 문제는 중복이 불가능하고 순서대로 사용해야 한다는 점에서 Queue를 이용하여 풀었습니다. 
추억 점수는 이중 for문으로 풀었습니다.

feat: Orena 250416 2문제

---

shong69/250416_추억 점수.java
shong69/250416_카트_뭉치.java

카드뭉치에서는 Queue를 통해 fifo구조를 사용하였습니다.
추억 점수는 이중 for문을 사용하였습니다.

feat: shong69 250416 2문제

---

nojong99/250416_추억_점수.java
nojong99/250416_카드_뭉치.java

카드 뭉치 문제는 Arrays.equals를 이용해 마지막 비교를 하였고, 
추억 점수 문제를 3중 for문을 통해 해결하였습니다.

feat: nojong99 250416 2문제

---

HbinAhn/250416_추억_점수.java
HbinAhn/250416_카드_뭉치.java

feat: HbinAhn 250416 2문제

---

nojong99/250417_2016년.java
nojong99/250417_폰켓몬.java

폰켓몬 문제는 set으로 2016년 문제는 배열에 값을 담아 해결하였습니다.

feat: nojong99 250417 2문제

---

Orena/250417_2016년.java
Orena/250417_폰켓몬.java

2016년 문제는 한 달을 배열로 만들어 풀었고 폰켓몬 문제는 HashSet에 배열을 넣어 풀었습니다.

feat: Orena 250417 2문제

---

minho00123/250417_2016년.java
minho00123/250417_폰켓몬.java

폰켓몬은 Set을 이용하였고, 2016년은 날짜와 요일을 배열로 선언해서 풀이를 진행하였습니다.

feat: minho00123 250417 2문제

---

shong69/250417_2016년.java
shong69/250417_폰켓몬.java

폰켓몬에서는 stream과Collections를 사용해 Set으로 변경해 사용하였습니다.
2016년 문제에서는 해당 일까지의 전체 일수를 구한 후 7로 나누어 요일을 알아내었습니다.

feat: shong69 250417 2문제

---

HbinAhn/250417_2016년.java
HbinAhn/250417_폰켓몬.java

feat: HbinAhn 250417 2문제

---

99MotiveU/250417_2016년.java
99MotiveU/250417_폰켓몬.java

폰켓몬은 HashSet, 2016년은 배열을 이용해 해결했습니다.

feat: 99MotiveU 250417 2문제

---

99MotiveU/250418_기사단원의_무기.java

feat: 99MotiveU 250418 1문제

---

Orena/250418_기사단원의_무기.java

약수를 구할 때 효율적으로 구하는 방법을 공부하게 되었습니다.

feat: Orena 250418 1문제

---

minho00123/250418_기사단원의_무기.java

feat: minho00123 250418 1문제

---

nojong99/250418_기사단원의_무기.java

기사 단원 문제는 약수의 개수를 따로 구한 후 저장해 계산하였습니다.

feat: nojong99 250418 1문제

---

HbinAhn/250418_기사단원의_무기.java

시간초과 해결하기가 어려웠네요ㅜㅜ 결국 다양한 풀이방법 찾아보고 이해해서 풀어봤습니다.

feat: HbinAhn 250418 1문제

---

shong69/250418_기사단원의_무기.java
shong69/250419_과일_장수.java
shong69/250419_모의고사.java

4/18- 기사단원의 무기
4/19- 과일장수 :배열의 copyOfRange()를 사용 / 모의고사: 경우의 수 모두 구하여 정답 리턴

feat: shong69 250419 3문제

---

minho00123/250419_과일_장수.java
minho00123/250419_모의고사.java
minho00123/250421_덧칠하기.java

모의고사 문제는 수포자들의 답을 각각 배열로 만들어 해당 값이 값이 정답이면 갯수를 증가시키는 풀이로 진행하였습니다.
과일 장수 문제는 내림차순으로 배열을 정렬한 후, 상자에 넣을 수 있는 값만큼만 반복문을 돌며 최대 이익을 계산하였습니다.
덧칠하기 문제는 칠할 수 있는 범위를 인덱스로 바꿔 가면서 풀이를 진행하였습니다.

feat: minho00123 250421 3문제

---

Orena/250419_과일_장수.java
Orena/250419_모의고사.java
Orena/250421_덧칠하기.java

19일, 21일 총 3문제입니다.
과일 장수는 2중 for문으로 배열에 담아 풀었고 모의고사는 test()를 만들어 반복하고 list에 담아 최대값을 비교해 풀었습니다.
덧칠하기는 칠해진 마지막 칸과 칠해야 할 칸을 비교하는 조건을 이용해 풀었습니다.

feat: Orena 250421 3문제

---

minho00123/250422_소수_만들기.java
minho00123/250422_소수_찾기.java

소수 찾기는 시간초과를 해결하기 위해 [에라토스테네스의 체](https://ko.wikipedia.org/wiki/%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98_%EC%B2%B4)를 참고하여 풀이를 진행하였습니다.
소수 만들기는 다중 for문을 이용하여 풀었습니다.

feat: minho00123 250422 2문제

---

nojong99/250422_소수_만들기.java
nojong99/250422_소수_찾기.java

소수 찾기는 소수를 구하는 for문에서 비교하는 부분을 제곱시켜 시간 초과 문제를 해결했습니다.
소수 만들기 문제는 다중 for문을 통해 해결하였습니다.

feat: nojong99 250422 2문제

---

Orena/250423_옹알이(2).java

가능한 조합을 저장해서 비교하고 싶었는데 시간 초과 문제가 있어 문자열을 바로 비교하는 방법으로 풀었습니다.

feat: Orena 250423 1문제

---

99MotiveU/250423_옹알이(2).java
99MotiveU/250424_실패율.java

옹알이(2) 문제 우선 원본 babbling배열을 직접 수정하지 않기 위해 temp로 복사하고 반복문을 돌면서 같은 발음이 연속으로 있는지 검사하여 있다면 continue를 사용해 다음 단어로 넘어가고, 없다면 유효한 발음을 공백으로 바꿔줍니다. 이후 공백을 제외한 문자가 남아 있지 않다면 answer를 증가 시키는 식으로 해결했습니다.

feat: 99MotiveU 250423 1문제

---

nojong99/250423_옹알이_(2).java

문제 해결이 어려워 검색의 도움을 받아 해결하였습니다. 재귀 함수를 구현하는 방법을 알게 되었습니다.

feat: nojong99 250423 1문제

---

HbinAhn/250422_소수_만들기.java
HbinAhn/250422_소수_찾기.java

소수 찾기는 결국 에라토스테네스의 체를 찾아서 소수 구하는 법을 이해해서 풀었고,
소수 만들기는 소수 찾기에서 찾은 내용을 메서드로 활용하여 풀어봤습니다.
이번 문제를 계기로 소수를 좀 더 이해하게 되었습니다.

feat: HbinAhn 250422 2문제

---

shong69/250424_실패율.java

Comparable 인터페이스를 상속받아 정렬을 구현하였습니다.

feat: shong69 250424 1문제

---

Orena/250424_실패율.java

실패율을 map에 key값을 스테이지로, value를 실패율로 하여 저장하고 value를 내림차순으로 정렬한 뒤 key값을 answer에 넣어주었습니다.

feat: Orena 250424 1문제

---

minho00123/250424_실패율.java

feat: minho00123 250424 1문제

---

minho00123/250425_PCCE_기출문제_9번_지폐_접기.java

문제에 나온 의사 코드를 바탕으로 풀이를 진행하였습니다.

feat: minho00123 250425 1문제

---

shong69/250425_[PCCE_기출문제]_9번_지폐_접기.java

feat: shong69 250425 1문제

---

Orena/250426_다트_게임.java
Orena/250426_로또의_최고_순위와_최저_순위.java
Orena/250428_문자열_나누기.java

26일 2문제, 28일 1문제입니다.
다트 게임은 tokenizer 와 contains를 이용해서 풀었고
로또는 배열로 맞는 숫자를 count 한 뒤 switch-case문을 이용해 풀었습니다.
문자열 나누기는 charAt으로 같은 문자 갯수와 다른 문자 갯수를 세는 방식으로 풀었습니다.

feat: Orena 250428 3문제

---

shong69/250421_덧칠하기.java
shong69/250428_문자열_나누기.java

다트 게임 : while문을 통해 각 경우에 맞게 조건을 처리하였습니다.
최고 순위와 최저순위 : 현재 조건에서 최고가 되는 경우와 최저가 되는 경우를 각각 구하였습니다. 순위 조건은 삼항 연산자를 통해 구하였습니다.

feat: shong69 250426 2문제

---

nojong99/250426_다트_게임.java
nojong99/250426_로또의_최고_순위와_최저_순위.java
nojong99/250428_문자열_나누기.java

다트 게임은 isDigit으로 정수를 판별하고, 각 점수를 배열에 넣어 구현하였습니다. 
로또의 최고 순위와 최저 순위 문제는 조건문을 넣어 해결하였습니다. 
문자열 나누기 문제는 substirng으로 값을 파해서 구하였습니다.

feat: nojong99 250428 3문제

---

Orena/250429_둘만의_암호.java

contain 함수 사용하고 싶어서 HashSet에 skip 문자열을 넣고 풀었습니다.

feat: Orena 250429 1문제

---

minho00123/250429_둘만의_암호.java

Boolean 배열을 만들어 스킵할 문자의 위치를 표시한 후에, 반복문을 돌면서 실질적으로 더해야할 index 값을 찾으면서 문제 풀이를 진행하였습니다.

feat: minho00123 250429 1문제

---

shong69/250429_둘만의_암호.java

Set을 활용하여 시간복잡도를 O(1)로 줄일 수 있었습니다.
while을 통해 조건을 충족해야 index를 채우는 방식을 사용하였습니다.

feat: shong69 250429 1문제

---

99MotiveU/250429_둘만의_암호.java
99MotiveU/250430_대충_만든_자판.java

둘만의 암호는 charAt과 indexOf를 사용해 문제 설명에 적힌 내용을 코드로 옮겨 해결했습니다.

feat: 99MotiveU 250429 1문제

---

nojong99/250429_둘만의_암호.java

숫자를 1씩 증가하게 했고, z범위가 벗어나면 a로 돌아가게 조건을 넣어  문제를 해결했습니다.

feat: nojong99 250429 1문제

---

minho00123/250430_대충_만든_자판.java

Map을 이용하여 Key 값으로는 문자, Value 값으로는 index를 넣어 풀이를 진행하였습니다.

feat: minho00123 250430 1문제

---

Orena/250430_대충_만든_자판.java

targets를 char 배열로 바꾼 뒤 인덱스를 제어하는 방법으로 풀었습니다.

feat: Orena 250430 1문제

---

nojong99/250430_대충_만든_자판.java

삼중 for문을 사용하였습니다. 초기 val 값을 -1로 두고, 문자가 해당 리스트에 포함되었을 때 비교를 하고 for문을 돌며 나올수록 최소값을 저장할 수 있게 문제를 해결하였습니다.

feat: nojong99 250430 1문제

---

99MotiveU/250501_이웃한_칸.java

feat: 99MotiveU 250501 1문제

---

Orena/250501_이웃한_칸.java

feat: Orena 250501 1문제

---

minho00123/250501_PCCE_기출문제_9번_이웃한_칸.java

문제에서 제공된 의사코드를 바탕으로 문제를 풀이하였습니다.

feat: minho00123 250501 1문제

---

Orena/250502_완주하지_못한_선수.java

참가자 배열을 hashmap에 넣어서 비교해가며 풀었습니다.

feat: Orena 250502 1문제

---

minho00123/250502_완주하지_못한_선수.java

배열을 정렬하여 만약 둘의 이름이 같다면 인덱스를 증가하는 식을 풀이 하였습니다.

feat: minho00123 250502 1문제

---

nojong99/250501_PCCE_기출문제_9번_이웃한_칸.java
nojong99/250502_완주하지_못한_선수.java
nojong99/250503_체육복.java
nojong99/250505_숫자_짝꿍.java
nojong99/250506_햄버거_만들기.java

이웃한 칸, 완주하지 못한 선수, 체육복, 숫자 짝꿍, 햄버거 만들기 5개 문제 입니다.

feat: nojong99 250506 5문제

---

99MotiveU/250502_완주하지_못한_선수.java
99MotiveU/250503_체육복.java
99MotiveU/250505_숫자_짝꿍.java
99MotiveU/250506_햄버거_만들기.java
99MotiveU/250507_데이터_분석.java

완주하지 못한 선수 문제는 Arrays클래스의 sort()메서드를 이용해 해결했습니다.

feat: 99MotiveU 250502 1문제

---

shong69/250502_완주하지_못한_선수.java
shong69/250503_체육복.java
shong69/250505_숫자_짝꿍.java
shong69/250506_햄버거_만들기.java

완주하지 못한 선수, 체육복, 숫자 짝꿍, 햄버거 만들기 네 문제 입니다.

feat:shong69 250506 4문제

---

Orena/250503_체육복.java
Orena/250505_숫자_짝꿍.java
Orena/250506_햄버거_만들기.java
Orena/250507_데이터_분석.java

5/3~5/7까지 총 4문제입니다.
체육복, 숫자 짝꿍, 햄버거 만들기, 데이터 분석 문제입니다.

feat: Orena 250507 4문제

---

minho00123/250503_체육복.java
minho00123/250505_숫자_짝꿍.java
minho00123/250506_햄버거_만들기.java
minho00123/250507_PCCE_기출문제_10번_데이터_분석.java

체육복, 숫자 짝꿍, 햄버거 만들기, 데이터 분석 총 4문제 문제 풀이 올립니다.

feat: minho00123 250507 4문제

---

99MotiveU/250508_크레인_인형_뽑기.java

feat: 99MotiveU 250508 1문제

---

Orena/250508_크레인_인형뽑기_게임.java
Orena/250509_키패드_누르기.java

8일, 9일 2문제입니다.
인형뽑기는 stack을 이용해서 풀었고
키패드는 키패드를 배열로 만든 뒤 좌표를 map에 넣어 거리를 계산하도록 했습니다.

feat: Orena 250509 2문제

---

Orena/250510_성격_유형_검사하기.java
Orena/250510_신규_아이디_추천.java
Orena/250512_바탕화면_정리.java

10일 2문제,12일 1문제 입니다.
성격 유형 검사는 조건문으로 만들었고
신규아이디 추천은 문제의 단계별로 하나씩 수행하도록 만들었습니다.
바탕화면 정리는 max와 min값을 활용하여 풀었습니다.

feat: Orena 250512 3문제

---

shong69/250509_키패드_누르기.java
shong69/250510_성격_유형_검사하기.java
shong69/250510_신규_아이디_추천.java
shong69/250512_바탕화면_정리.java

5/9 키패드 누르기 : 절대값인 거리를/3 한 값과 전과 같은 거리를%3한 값을 더하여 실제 거리를 구하였습니다.
5/10 성격 유형 검사하기 : Map을 사용하여 값을 저장하고 찾을 수 있었습니다.
신규 아이디 추천 : 정규표현식과 여러 메서드를 통해 값을 정제하였습니다.
5/12 바탕화면 정리 : 격자를 이중 for문으로 돌면서 각각 최소값과 최대값을 구하였습니다.

feat: shong69 250512 4문제

---

minho00123/250508_크레인_인형뽑기_게임.java
minho00123/250509_키패드_누르기.java
minho00123/250510_성격_유형_검사하기.java
minho00123/250510_신규_아이디_추천.java
minho00123/250512_바탕화면_정리.java
minho00123/250513_개인정보_수집_유효기간.java

5월 8일 문제인 "크레인 인형뽑기 게임"와 5월 9일 문제인 "키패드 누르기" 2문제 입니다.
크레인 인형뽑기는 스택을 이용하였고,
키패드 누르기는 모든 경우의 수를 바탕으로 조건문을 통해 풀었습니다.

feat: minho00123 250509 2문제

---

Orena/250513_개인정보_수집_유효기간.java

split과 parseInt로 배열을 만든 뒤 날짜 계산의 조건을 만들어서 풀었습니다.

feat: Orena 250513 1문제

---

99MotiveU/250513_개인정보_수집_유효기간.java

개인정보 수집 유효기간은 약관별 유효기간을 Map에 저장한 뒤, 각 개인정보 수집일에 유효기간을 더해 만료일을 계산하고, 오늘 날짜와 비교하여 만료된 개인정보의 번호를 리스트에 담아 배열로 변환해 해결했습니다.

feat: 99MotiveU 250513 1문제

---

README.md

앞으로 문제는 노션이 아닌 GitHub에 올리도록 하겠습니다.
매주 문제는 그 전주 금요일날 정해서 올리도록 하겠습니다.

docs: Week9 문제 추가

---

Orena/250514_유연근무제.java

출근 인정시간(10분 더하기)을 계산해서 배열로 만들고 실제 출근 시간과 비교해서 풀었습니다

feat: Orena 250514 1문제

---

minho00123/250514_유연근무제.java

10분을 추가한 시간을 계산하여 문제 풀이를 진행하였습니다.

feat: minho00123 250514 1문제

---

shong69/250514_유연근무제.java

feat: shong69 250514 1문제

---

shong69/250515_달리기_경주.java

HashMap을 사용하여 시간복잡도 문제를 해결하였습니다.

feat: shong69 250515 1문제

---

Orena/250515_달리기_경주.java

map에 현재 위치의 인덱스를 담아 배열을 이동하며 풀었습니다

feat: Orena 250515 1문제

---

99MotiveU/250515_달리기_경주.java

달리기 경주 문제는  HashMap과 반복문을 이용해 풀이했습니다.

feat: 99MotiveU 250515 1문제

---

minho00123/250515_달리기_경주.java

feat: minho00123 250515 1문제

---

shong69/250516_공원_산책.java

5/16: 공원 산책 
x, y 방향을 숫자 배열로 구분하여 dx dy 문제 유형에 맞는 방식을 사용하였습니다.
유효하지 않은 경우를 포함하는 이동이라면 해당 이동 자체가 초기화 됨을 유의하여 작성하였습니다.

feat: shong69 250516 1문제

---

Orena/250516_공원_산책.java

지도를 int배열로 만들고 이동을 조건으로 만들어 풀었습니다

feat: Orena 250516 1문제

---

minho00123/250516_공원_산책.java

각 조건에 맞는 조건문을 사용하여 문제를 풀이하였습니다.

feat: minho00123 250516 1문제

---

Orena/250517_공원.java
Orena/250517_붕대_감기.java
Orena/250519_신고_결과_받기.java

공원 문제는 2중 배열을 반복문으로 돌며 조건을 만들어 풀었고 
붕대 감기는 문제에 제시된 조건을 그대로 만들어 풀었습니다.
신고 결과 받기는 Set, Map, List를 이용해서 조건에 맞게 각 자료에 넣어가며 풀었습니다.

feat: Orena 250519 3문제

---

minho00123/250517_PCCE_기출문제_10번_공원.java
minho00123/250517_PCCP_기출문제_1번_붕대_감기.java
minho00123/250519_신고_결과_받기.java

feat: minho00123 250519 3문제

---

99MotiveU/250516_공원_산책.java
99MotiveU/250517_공원.java
99MotiveU/250517_붕대_감기.java
99MotiveU/250519_신고_결과_받기.java
99MotiveU/250520_동영상_재생기.java

16일 1문제, 17일 2문제, 19일 1문제 총 4문제 올립니다.

feat: 99MotiveU 250519 4문제

---

minho00123/250520_PCCP_기출문제_1번_동영상_재생기.java
minho00123/250521_택배_상자_꺼내기.java

feat: minho00123 250521 2문제

---

Orena/250520_동영상_재생기.java
Orena/250521_택배_상자_꺼내기.java

20일, 21일 1문제씩 총 2문제입니다
동영상 재생기는 int 배열과 초 단위 계산을 활용하여 풀었고
택배 상자 꺼내기는 int 2중 배열을 이용하여 풀었습니다.

feat: Orena 250521 2문제

---

shong69/250521_택배_상자_꺼내기.java

feat:shong69 250521 1문제

---

Orena/250522_가장_많이_받은_선물.java

feat: Orena 250522 1문제

---

99MotiveU/250521_택배_상자_꺼내기.java
99MotiveU/250522_가장_많이_받은_선물.java

택배 상자 꺼내기 문제는 상자의 배치 규칙에 따라 num이 위치한 좌표를 구하고, 해당 열을 따라 위층을 확인하면서 꺼내야 하는 상자 수를 세는 방식으로 해결했습니다.

feat: 99MotiveU 250521 1문제

---

minho00123/250523_올바른_괄호.java
minho00123/250523_최댓값과_최솟값.java
minho00123/250523_최솟값_만들기.java
minho00123/250524_JadenCase_문자열_만들기.java
minho00123/250524_다음_큰_숫자.java
minho00123/250524_숫자의_표현.java
minho00123/250524_이진_변환_반복하기.java

feat: minho00123 250526 7문제

---

일정표.md

README.md에 있던 Week10 문제 이동입니다.

docs: Week10 문제 이동

---

Orena/250614_구명보트.java
Orena/250616_귤_고르기.java
Orena/250617_멀리_뛰기.java

feat: Orena 250617 3문제

---

nojong99/250616_귤_고르기.java
nojong99/250617_멀리_뛰기.java

귤 고르기 문제는 Map과 getOrDefault를 사용해 현재 수량을 파악한 후 정렬을 통해 문제를 해결했습니다. 
멀리 뛰기 문제는 동적 계획법으로 문제를 해결하였습니다.

feat: nojong99 250617 2문제

---

Orena/250618_N개의_최소공배수.java
Orena/250619_영어_끝말잇기.java
Orena/250620_예상_대진표.java
Orena/250621_연속_부분_수열_합의_개수.java
Orena/250623_할인_행사.java
Orena/250624_괄호_회전하기.java

feat: Orena 250624 6문제

---

minho00123/250618_N개의_최소공배수.java
minho00123/250619_영어_끝말잇기.java
minho00123/250620_예상_대진표.java
minho00123/250621_연속_부분_수열_합의_개수.java
minho00123/250623_할인_행사.java
minho00123/250624_괄호_회전하기.java

6월 18일 부터 6월 24일 까지 총 6문제 올립니다.

feat: minho00123 250624 6문제

---

Orena/250625_n^2_배열_자르기.java

feat: Orena 250625 1문제

---

nojong99/250618_N개의_최소공배수.java
nojong99/250619_영어_끝말잇기.java
nojong99/250620_예상_대진표.java
nojong99/250621_연속_부분_수열_합의_개수.java
nojong99/250623_할인_행사.java
nojong99/250624_괄호_회전하기.java

feat: nojong99 250624 6문제

---

Orena/250626_행렬의_곱셈.java

feat: Orena 250626 1문제

---

minho00123/250626_행렬의_곱셈.java

행렬의 곱셈 문제 입니다.
3중 반복문으로 풀이를 진행하였습니다.

feat: minho00123 250626 1문제

---

Orena/250627_H-Index.java

내림차순으로 정렬하여 H-Index의 조건에 맞게 풀었습니다

feat: Orena 250627 1문제

---

minho00123/250627_H-Index.java

feat: minho00123 250627 1문제

---

Orena/250628_의상.java
Orena/250630_기능개발.java
Orena/250702_피로도.java

feat: Orena 250630 1문제

---

minho00123/250628_의상.java
minho00123/250630_기능개발.java
minho00123/250702_피로도.java

6월 28일, 6월 30일, 7월 2일 문제 올립니다.

feat: minho00123 250702 3문제

---

99MotiveU/250630_기능_개발.java

feat: 99MotiveU 250630 1문제

---

Orena/250704_캐시.java

feat: Orena 250704 1문제

---

99MotiveU/250707_튜플.java

7월7일 튜플 문제는 Substring()과 Split()을 사용해 문자열 파싱 한 후, sort()로 정렬했습니다. 그 뒤 HashSet으로 중복을 제거하며 ArrayList에 순서대로 값을 저장한 후 stream().mapToInt()라는 메서드로 배열 변환해 해결했습니다.

feat: 99MotiveU 250707 1문제

---

Orena/250714_롤케이크_자르기.java

롤케이크 자르기 Map으로 양쪽에서 count하여 풀었습니다.

feat: Orena 250714 1문제

---

99MotiveU/250709_전화번호 목록.java

feat: 99MotiveU 250709 1문제

---

minho00123/250719_게임_맵_최단거리.java

게임 맵 최단거리 문제 입니다.
BFS를 이용하여 문제 풀이 진행하였습니다.

feat: minho00123 250719 1문제

---

99MotiveU/250711_프로세스.java

7.11 프로제스 문제입니다. 큐를 사용해 해결했습니다.

feat: 99MotiveU 250711 1문제

---

Orena/250726_타겟_넘버.java

feat: Orena 250727 1문제

---

Orena/250901_뉴스_클러스터링.java

자카드 유사도 개념을 배웠고 이해가 조금 더 필요할 것 같습니다.

feat: Orena 250902 1문제

---

99MotiveU/205719_게임_맵_최단거리.java

7/ 19 게임 맵 최단거리 문제입니다. 밀린 문제가 많은데,  한 문제씩 계속 pr하겠습니다.

feat: 99MotiveU 250719 1문제
